package co.harlequinmettle.healthfoodconcepts;
 


public interface FG2_I {
	//72    American Indian/Alaska Native Foods
	public static final String[] FG_0 = {
	"acorn stew (apache)",
	"agave",
	"agutuk",
	"ascidians",
	"bear",
	"blackberries",
	"blueberries",
	"bread",
	"buffalo",
	"caribou",
	"cattail",
	"chilchen",
	"chiton",
	"chokecherries",
	"cloudberries",
	"cockles",
	"corn", 
	"cornmeal",
	"cranberries",
	"cranberry",
	"deer",
	"duck",
	"elk",
	"fireweed",
	"fish",
	"frybread",
	"hazelnuts",
	"huckleberries",
	"lambsquarters",
	"mashu roots",
	"melon",
	"moose",
	"mouse nuts",
	"mush",
	"mutton",
	"octopus",
	"oil",
	"oopah",
	"owl",
	"piki bread",
	"pinon nuts",
	"plains pricklypear",
	"plums",
	"prairie turnips",
	"raspberries",
	"rhubarb",
	"rose hips",
	"salmon",
	"salmonberries",
	"sea cucumber",
	"sea lion",
	"seal",
	"smelt",
	"soup",
	"sourdock",
	"squash",
	"squirrel",
	"steelhead trout",
	"stew",
	"stew/soup",
	"stinging nettles",
	"tamales",
	"tamales",
	"tea",
	"tennis bread",
	"tortilla",
	"walrus",
	"whale",
	"willow",
	"wocas",
	};

	//46    Baby Foods
	public static final String[] FG_1 = { 
	"abbott nutrition",
	"apple",
	"apple-banana",
	"apple-cranberry",
	"apples",
	"baked",
	"banana",
	"beverage",
	"carrots",
	"cereal",
	"cherry",
	"cookie",
	"cookies",
	"corn",
	"crackers",
	"dessert",
	"dinner",
	"electrolyte",
	"fortified",
	"fruit",
	"grape",
	"green",
	"juice",
	"macaroni",
	"mashed",
	"mead johnson",
	"meat",
	"mixed",
	"nestle",
	"oatmeal",
	"pbm",
	"peaches",
	"pears",
	"peas",
	"plums",
	"potatoes",
	"pretzels",
	"prunes",
	"ravioli",
	"rice",
	"snack",
	"teething",
	"vegetable", 
	"yogurt",
	"zwieback"
	};

	//355    Baked Products
	public static final String[] FG_2 = {
	 
	"all-bran", 
	"angelfood",  
	"apple",
	"archway", 
	"austin",
	"bagel", 
	"baked",  
	"baking powder",
	"baking soda",
	"banana",  
	"bear naked", 
	"biscuits",
	"blueberry",  
	"bread",
	"bread crumbs",
	"bread sticks",
	"bread stuffing",
	"breakfast tart", 
	"brownberry",
	"brownies",
	"buckwheat",
	"butter",
	"buttermilk", 
	"cake",    
	"cheese", 
	"cheez-it",
	"cherry", 
	"chips deluxe",
	"chocolate",  
	"cinnamon",  
	"club", 
	"coconut", 
	"coffeecake",
	"continental mills", 
	"cookies",
	"corn",
	"corn flakes",
	"cornbread", 
	"cracked-wheat", 
	"cracker",
	"cream", 
	"cream puff",    
	"croissants",
	"croutons",  
	"danish",   
	"doughnuts",    
	"eclair", 
	"egg", 
	"eggo", 
	"english muffins",  
	"famous amos",
	"fig bars",
	"focaccia",
	"fortune",
	"french", 
	"fried pies",  
	"frozen",
	"fruit", 
	"fruitcake",
	"fudge",   
	"george weston",
	"gingerbread", 
	"gingersnaps",
	"girl scouts",
	"graham crackers",
	"grahams", 
	"gripz",    
	"hush puppies",
	"ice cream",  
	"iced oatmeal", 
	"irish soda",
	"italian",  
	"jackson's", 
	"kashi", 
	"keebler", 
	"keikitos", 
	"kellogg", 
	"kraft",    
	"ladyfingers", 
	"leavening agents",
	"lemon", 
	"little debbie",
	"low fat",   
	"martha white", 
	"matzo", 
	"melba toast",
	"milk",   
	"mixed-grain", 
	"molasses",
	"mother's",
	"muffin", 
	"multi-grain", 
	"murray",
	"nabisco",  
	"oat bran",
	"oatmeal", 
	"old fashioned",
	"pan dulce",
	"pancakes",  
	"pastry",  
	"peanut butter",
	"pecan",
	"phyllo dough",
	"pie", 
	"pillsbury",  
	"pita",
	"plain", 
	"pop-tarts", 
	"popovers", 
	"pound",   
	"pudding",
	"puff pastry",
	"pumpernickel",
	"pumpkin",
	"raisin", 
	"raspberry", 
	"ready crust",
	"ready-to-bake",
	"reduced fat",
	"reduced-calorie",
	"refrigerated",
	"rice bran",
	"rolls",
	"rusk toast",
	"rye",
	"saltines",   
	"sandies", 
	"shortbread",  
	"snack",  
	"southern kitchen",
	"special dietary",
	"special k",
	"sponge",   
	"strudel",
	"sugar", 
	"sunshine", 
	"sweet rolls",
	"taco shells",  
	"thomas english", 
	"toast",  
	"tortillas",
	"tostada shells",
	"town house",  
	"usda commodity",
	"vanilla",  
	"waffle", 
	"weight watcher",
	"wheat",  
	"white",
	"whole-wheat",  
	"wonton wrappers",
	"yeast", 
	"yellow",
	"zesta",
	};

	//44    Beef Products
	public static final String[] FG_3 = {
	"australian",
	"beef",
	"bottom sirloin",
	"brisket",
	"carcass",
	"chuck",
	"chuck eye",
	"chuck for stew",
	"composite of trimmed retail cuts",
	"cured",
	"flank",
	"grass-fed",
	"ground",
	"loin",
	"plate",
	"plate steak",
	"retail cuts",
	"rib",
	"rib eye",
	"ribeye",
	"round",
	"sandwich steaks",
	"shank crosscuts",
	"short loin",
	"shoulder pot roast",
	"shoulder pot roast or steak",
	"shoulder steak",
	"shoulder top blade steak",
	"tenderloin",
	"top loin filet",
	"top loin petite roast",
	"top loin petite roast/filet",
	"top sirloin",
	"usda commodity",
	"variety meats and by-products",
	};

	//115    Beverages
	public static final String[] FG_4 = {
	"acai",
	"alcoholic",
	"amp",
	"beef",
	"beer",
	"berry",
	"black",
	"bottled",
	"breakfast",
	"brewed",
	"canned",
	"carbonated",
	"carob-flavor",
	"chocolate",
	"citrus",
	"cocktail",
	"cocoa",
	"coffee",
	"cola",
	"cranberry",
	"daiquiri",
	"dairy",
	"diet",
	"distilled",
	"drink",
	"eggnog-flavor",
	"energy",
	"fast",
	"flavored",
	"frozen",
	"fruit",
	"fruit-flavored",
	"full throttle",
	"gatorade",
	"ginger ale",
	"grape", 
	"guava",
	"herb",
	"hibiscus",
	"horchata", 
	"instant",
	"lemon-lime",
	"lemonade",
	"lemonade-flavor", 
	"limeade",
	"liqueur", 
	"malt", 
	"mango",  
	"monster",
	"natural",
	"nestle", 
	"non-alcoholic",
	"non-carbonated",
	"orange",
	"orange-flavor", 
	"peach",
	"pepper-type", 
	"pina colada",
	"pineapple",
	"powder",
	"powerade",
	"propel",
	"quaker",
	"ready-to-drink",
	"red",
	"reduced",
	"rice",
	"rockstar",
	"root beer",
	"shake",
	"sports",
	"sprite",
	"strawberry",
	"strawberry-flavor",
	"tap water",
	"tea", 
	"tropical",
	"unsweetened",
	"v8",
	"vault",
	"vegetable",
	"water", 
	"whiskey",
	"wine", 
	};

	//108    Breakfast Cereals
	public static final String[] FG_5 = {
	"alpen",
	"amaranth flakes",
	"bear naked banana nut",
	"bear naked cranberry raisin",
	"bear naked nut cluster crunch",
	"bran flakes",
	"cereals",
	"chocolate-flavored frosted puffed corn",
	"corn flakes",
	"corn grits",
	"cranberry macadamia nut cereal",
	"cream of rice",
	"cream of wheat",
	"crispy brown rice",
	"dry mix (corn and soy flours)",
	"familia",
	"farina",
	"frosted oat cereal with marshmallows",
	"general mills",
	"general mills cinnamon chex",
	"general mills corn chex",
	"general mills total plus omega-3",
	"granola",
	"health valley",
	"incaparina",
	"kashi",
	"kashi 7 whole grain flakes",
	"kashi 7 whole grain honey puffs",
	"kashi 7 whole grain nuggets",
	"kashi 7 whole grain puffs",
	"kashi berry blossom",
	"kashi go lean crunch!",
	"kashi go lean hot cereal",
	"kashi golden goodness",
	"kashi golean",
	"kashi golean crisp cinnamon crumble",
	"kashi golean crisp toasted berry crumble",
	"kashi golean crunch!",
	"kashi good friends",
	"kashi granola",
	"kashi heart to heart",
	"kashi honey sunshine",
	"kashi indigo morning",
	"kashi organic promise",
	"kashi simply maize",
	"kellogg",
	"kellogg's",
	"kellogg's corn flakes",
	"kellogg's crunchy nut golden honey nut flakes",
	"kellogg's crunchy nut roasted nut and honey o's",
	"kellogg's fiberplus berry yogurt crunch",
	"kellogg's fiberplus cinnamon oat crunch",
	"kellogg's frosted mini-wheats",
	"kellogg's frosted mini-wheats bite size blueberry muffin",
	"kellogg's frosted mini-wheats bite size cinnamon streusel",
	"kellogg's frosted mini-wheats little bites",
	"kellogg's frosted mini-wheats touch of fruit in the middle mixed",
	"kellogg's krave chocolate cereal",
	"kellogg's pops mixit cereal",
	"kellogg's rice krispies",
	"kellogg's special k chocolatey delight",
	"kellogg's special k multigrain oats and honey",
	"malt-o-meal",
	"malt-o-meal honey graham squares",
	"maltex",
	"marshmallow alpha-bits",
	"maypo",
	"millet",
	"muesli",
	"natural granola apple cranberry almond",
	"nature's path",
	"nestum",
	"oat",
	"oat bran",
	"oat bran flakes",
	"oats",
	"post",
	"post blueberry morning",
	"post great grains banana nut crunch",
	"post great grains cranberry almond crunch",
	"post honey bunches of oats with vanilla bunches",
	"post raisin bran cereal",
	"post toasties corn flakes",
	"puffed",
	"quaker",
	"quaker squares",
	"ralston",
	"ralston corn biscuits",
	"ralston corn flakes",
	"ralston crispy hexagons",
	"ralston crispy rice",
	"ralston enriched bran flakes",
	"ralston tasteeos",
	"rice",
	"rolled oats",
	"roman meal",
	"roman meal with oats",
	"sun country",
	"uncle sam cereal",
	"usda commodity corn and rice (includes all commodity brands)",
	"usda commodity rice crisps (includes all commodity brands)",
	"waffelos",
	"weetabix whole wheat cereal",
	"wheat",
	"wheat and bran",
	"wheat germ",
	"wheatena",
	"whole wheat hot natural cereal",
	};

	//31    Cereal Grains and Pasta
	public static final String[] FG_6 = {
	
	"amaranth",
	"arrowroot",
	"barley",
	"buckwheat",
	"bulgur",
	"corn",
	"cornmeal",
	"cornstarch",
	"couscous",
	"hominy",
	"kamut",
	"macaroni",
	"millet",
	"noodles",
	"oat",
	"oats",
	"pasta",
	"quinoa",
	"rice",
	"rye",
	"semolina",
	"sorghum",
	"spaghetti",
	"spelt",
	"tapioca",
	"teff",
	"triticale",
	"vital",
	"wheat",
	"wild",
	};

	//132    Dairy and Egg Products
	public static final String[] FG_7 = {
	"acid",
	"american",
	"anhydrous",
	"bar",
	"beverage",
	"blue",
	"brick",
	"brie",
	"butter",
	"butter oil",
	"buttermilk",
	"camembert",
	"canned",
	"caraway",
	"cheddar",
	"cheese",
	"cheese food",
	"cheese product",
	"cheese sauce",
	"cheese spread",
	"cheese substitute",
	"cheshire",
	"chocolate",
	"colby",
	"cold",
	"cottage",
	"cream",
	"cream substitute",
	"dessert topping",
	"dietetic",
	"dry",
	"duck",
	"dulce de",
	"edam",
	"egg",
	"egg mix",
	"egg substitute",
	"eggnog",
	"eggs",
	"ensure plus",
	"fat",
	"fat free",
	"feta",
	"filled",
	"flavored",
	"fluid",
	"fontina",
	"fresh",
	"frozen",
	"fruit",
	"gjetost",
	"goat",
	"goose",
	"gouda",
	"greek",
	"gruyere",
	"half",
	"human",
	"ice cream",
	"imitation",
	"imitation cheese",
	"indian",
	"instant",
	"kraft breakstone's",
	"kraft breyers",
	"kraft cheez",
	"kraft free",
	"kraft velveeta",
	"light",
	"limburger",
	"liquid",
	"low",
	"low-sodium",
	"lowfat",
	"made",
	"mexican",
	"milk",
	"milk dessert",
	"milk shakes",
	"milk substitutes",
	"milkshake",
	"monterey",
	"mozzarella",
	"muenster",
	"neufchatel",
	"no",
	"non-butterfat",
	"nonfat",
	"nutritional supplement",
	"parmesan",
	"parmesan cheese",
	"pasteurized",
	"plain",
	"port",
	"powder",
	"powdered",
	"prepared",
	"pressurized",
	"producer",
	"protein supplement",
	"provolone",
	"quail",
	"reddi wip",
	"reduced",
	"ricotta",
	"romano",
	"roquefort",
	"salted",
	"scrambled",
	"semi",
	"sheep",
	"soft",
	"sour",
	"sour cream",
	"sour dressing",
	"sweet",
	"swiss",
	"thick",
	"tilsit",
	"turkey",
	"usda",
	"usda commodity",
	"vanilla",
	"whey",
	"whipped",
	"whipped cream",
	"whipped topping",
	"white",
	"whole",
	"without",
	"yogurt",
	"yolk",
	};

	//207    Fast Foods
	public static final String[] FG_8 = {
	 
	"bacon", 
	"bagel",   
	"burger",
	"big mac",
	"biscuit", 
	"brownie",
	"burger king",
	"burrito", 
	"caesar salad", 
	"cheeseburger", 
	"chicken",  
	"chimichanga",
	"chocolate",
	"clams", 
	"coleslaw",
	"cookies",
	"corn",
	"crab cake", 
	"croissant", 
	"danish pastry", 
	"deluxe breakfast", 
	"digiorno pizza",
	"domino's", 
	"egg", 
	"enchilada",
	"enchirito",
	"english muffin",
	"entrees",
	"fast food",  
	"fish", 
	"french fries",
	"french toast",
	"fried chicken",
	"frijoles",
	"frosty dairy",
	"fruit", 
	"grape", 
	"ham", 
	"hamburger", 
	"hash brown", 
	"honey", 
	"hotcakes", 
	"hotdog",
	"hush puppies", 
	"ice cream",
	"kashi pizza",
	"kentucky fried chicken",  
	"little caesars",
	"low fat",
	"lowfat",
	"margherita", 
	"mcdonald's",   
	"mediterranean", 
	"nachos", 
	"onion rings", 
	"oysters",
	"pan crust",
	"pancakes",
	"papa john's",
	"peanuts",
	"pepperoni topping",
	"pizza",
	"pizza chain",
	"pizza hut",
	"popcorn chicken",
	"popeyes",
	"potato",   
	"quesadilla", 
	"roast beef",
	"roasted vegetable",
	"salad", 
	"sausage", 
	"scallops", 
	"shrimp",   
	"submarine sandwich",
	"sundae",  
	"taco bell",  
	"tostada", 
	"vanilla",  
	"wendy's",
	"whopper",
	"yogurt parfait",
	};

	//117    Fats and Oils
	public static final String[] FG_9 = {
	"70%",
	"80%",
	"almond",
	"animal fat",
	"approximately",
	"apricot",
	"avocado",
	"babassu",
	"bacon",
	"beef",
	"benecol",
	"blue",
	"butter",
	"butter replacement",
	"butter-margarine",
	"buttermilk",
	"caesar",
	"canola",
	"chicken",
	"cocoa",
	"coconut",
	"cod",
	"coleslaw",
	"confectionery",
	"cooking",
	"corn",
	"cottonseed",
	"creamy dressing",
	"cupu",
	"dressing",
	"duck",
	"fat",
	"fish oil",
	"flaxseed",
	"french",
	"goose",
	"grapeseed",
	"green",
	"hazelnut",
	"herring",
	"home",
	"honey",
	"household",
	"industrial",
	"italian",
	"kraft",
	"lard",
	"light",
	"low",
	"made",
	"margarine",
	"margarine spread",
	"margarine-butter",
	"margarine-like",
	"margarine-like shortening",
	"margarine-like spread",
	"margarine-like spread with yogurt",
	"margarine-like vegetable-oil spread",
	"margarine-type",
	"mayonnaise",
	"mayonnaise dressing",
	"mayonnaise-like",
	"meat drippings (lard",
	"menhaden",
	"multipurpose",
	"mustard",
	"mutton",
	"no",
	"nutmeg",
	"oat",
	"oil",
	"olive",
	"palm",
	"pam",
	"peanut",
	"peppercorn",
	"poppyseed",
	"ranch",
	"reduced",
	"reduced-calorie",
	"regular",
	"rice",
	"russian",
	"safflower",
	"salad dressing",
	"salmon",
	"sandwich spread",
	"sardine",
	"sesame",
	"sheanut",
	"shortening",
	"shortening bread",
	"shortening cake mix",
	"shortening confectionery",
	"shortening frying (heavy duty)",
	"shortening household soybean (hydrogenated) and palm",
	"shortening industrial",
	"smart",
	"soybean",
	"special",
	"spray-style",
	"stick/tub/bottle",
	"sunflower",
	"sweet",
	"teaseed",
	"thousand",
	"tomatoseed",
	"turkey",
	"ucuhuba",
	"usda commodity food",
	"vegetable",
	"vegetable oil",
	"vegetable oil-butter spread",
	"walnut",
	"wheat",
	"with",
	"without",
	};

	//86    Finfish and Shellfish Products
	public static final String[] FG_10 = {
	
	"abalone",
	"anchovy",
	"bass",
	"bluefish",
	"burbot",
	"butterfish",
	"carp",
	"catfish",
	"caviar",
	"cisco",
	"clam",
	"cod",
	"conch",
	"crab",
	"crayfish",
	"croaker",
	"cusk",
	"cuttlefish",
	"dolphinfish",
	"dried",
	"drum",
	"eel",
	"fish portions",
	"flatfish (flounder",
	"gefiltefish",
	"green",
	"grouper",
	"haddock",
	"halibut",
	"herring",
	"ling",
	"lingcod",
	"lobster",
	"mackerel",
	"milkfish",
	"monkfish",
	"mullet",
	"mussel",
	"ocean perch",
	"octopus",
	"oyster",
	"perch",
	"pike",
	"pollock",
	"pompano",
	"pout",
	"raw",
	"rockfish",
	"roe",
	"roughy",
	"sablefish",
	"salmon",
	"salmon nuggets",
	"sardine",
	"scallop",
	"scup",
	"sea bass",
	"seatrout",
	"shad",
	"shark",
	"sheepshead",
	"shrimp",
	"smelt",
	"snail",
	"snapper",
	"sockeye",
	"spiny lobster",
	"spot",
	"squid",
	"sturgeon",
	"sucker",
	"sunfish",
	"surimi",
	"swordfish",
	"tilapia",
	"tilefish",
	"trout",
	"tuna",
	"tuna salad",
	"turbot",
	"whelk",
	"whitefish",
	"whiting",
	"wolffish",
	"yellowtail",
	};

	//124    Fruits and Fruit Juices
	public static final String[] FG_11 = {
	
	"abiyuch",
	"acerola",
	"acerola juice",
	"apple juice",
	"apples",
	"applesauce",
	"apricot nectar",
	"apricots",
	"avocados",
	"bananas",
	"blackberries",
	"blackberry juice",
	"blueberries",
	"boysenberries",
	"breadfruit",
	"candied fruit",
	"carambola",
	"carissa",
	"cherimoya",
	"cherries",
	"clementines",
	"crabapples",
	"cranberries",
	"cranberry juice",
	"cranberry sauce",
	"cranberry-orange relish",
	"currants",
	"custard-apple",
	"dates",
	"durian",
	"elderberries",
	"feijoa",
	"figs",
	"fruit cocktail",
	"fruit salad",
	"gooseberries",
	"grape juice",
	"grape juice cocktail",
	"grapefruit",
	"grapefruit juice",
	"grapes",
	"groundcherries",
	"guanabana nectar",
	"guava nectar",
	"guava sauce",
	"guavas",
	"horned melon (kiwano)",
	"jackfruit",
	"java-plum",
	"juice",
	"jujube",
	"kiwifruit",
	"kumquats",
	"lemon juice",
	"lemon peel",
	"lemons",
	"lime juice",
	"limes",
	"litchis",
	"loganberries",
	"longans",
	"loquats",
	"mammy-apple",
	"mango nectar",
	"mangos",
	"mangosteen",
	"maraschino cherries",
	"melon balls",
	"melons",
	"mulberries",
	"nance",
	"naranjilla (lulo) pulp",
	"nectarines",
	"oheloberries",
	"olives",
	"orange juice",
	"orange peel",
	"orange pineapple juice blend",
	"orange-grapefruit juice",
	"oranges",
	"papaya",
	"papaya nectar",
	"papayas",
	"passion-fruit",
	"passion-fruit juice",
	"peach nectar",
	"peaches",
	"pear nectar",
	"pears",
	"persimmons",
	"pineapple",
	"pineapple juice",
	"pitanga",
	"plantains",
	"plums",
	"pomegranate juice",
	"pomegranates",
	"prickly pears",
	"prune juice",
	"prune puree",
	"prunes",
	"pummelo",
	"quinces",
	"raisins",
	"rambutan",
	"raspberries",
	"rhubarb",
	"rose-apples",
	"roselle",
	"rowal",
	"sapodilla",
	"sapote",
	"soursop",
	"strawberries",
	"sugar-apples",
	"tamarind nectar",
	"tamarinds",
	"tangerine juice",
	"tangerines",
	"usda commodity",
	"usda commodity peaches",
	"usda commodity pears",
	"watermelon",
	};

	//6    Lamb, Veal, and Game Products
	public static final String[] FG_12 = {
	
	"bison",
	"game meat",
	"goat",
	"lamb",
	"veal",
	};

	//256    Legumes and Legume Products
	public static final String[] FG_13 = {
	"adzuki",  
	"baked beans",    //secondary search
	"bean beverage",
	"beans", 
	"black", 
	"black turtle",
	"broadbeans (fava beans)",
	"burger",
	"campbell's", 
	"canned",
	"carob flour",
	"catjang", 
	"chickpea", 
	"chili",  
	"chocolate",     
	"cooked",
	"cowpeas",
	"cranberry (roman)",    
	"ensure", 
	"falafel",   
	"french",
	"fried",
	"frijoles rojos volteados", 
	"gardenburger",
	"great northern",    
	"hummus",
	"hyacinth beans",
	"kidney", 
	"lentils",
	"lima beans",  
	"loma linda",   
	"lupins",  
	"meat extender", 
	"meatless",
	"miso",
	"mori-nu",
	"morningstar farms", 
	"mothbeans",
	"mung beans",
	"mungo beans", 
	"nasoya",
	"natto",
	"navy", 
	"noodles",
	"okara",  
	"pace",
	"papad", 
	"peanut",
	"peas",
	"pigeon peas",
	"pink",
	"pinto", 
	"raw",  
	"refried beans",     
	"silk",   
	"soy flour",
	"soy meal",
	"soy protein concentrate",
	"soy protein isolate",
	"soy sauce",
	"soybean", 
	"soymilk", 
	"spanish peanut", 
	"split peas",   ///secondary 
	"tempeh", 
	"tofu", 
	"tofu yogurt",  
	"usda commodity",
	"valencia peanut",
	"vegetarian", 
	"veggie", 
	"vermicelli",
	"virginia peanut",// secondary
	"vitasoy", 
	"white beans",   //secondary
	"winged beans",
	"worthington",
	"yardlong beans",
	"yellow",
	};

	//38    Meals, Entrees, and Sidedishes
	public static final String[] FG_14 = {
	
	"beef",
	"beef pot pie",
	"beef stew",
	"burrito",
	"chicken",
	"chicken pot pie",
	"chicken tenders",
	"chili",
	"chili con carne with beans",
	"chili with beans",
	"corn dogs",
	"egg rolls",
	"hot pockets",
	"hot pockets ham 'n cheese stuffed sandwich",
	"kashi",
	"lasagna",
	"lasagna with meat & sauce",
	"lasagna with meat sauce",
	"lean pockets",
	"macaroni and cheese",
	"macaroni and cheese dinner with dry sauce mix",
	"pasta with meatballs in tomato sauce",
	"pasta with sliced franks in tomato sauce",
	"pasta with tomato sauce",
	"potato salad with egg",
	"pulled pork in barbecue sauce",
	"ravioli",
	"rice",
	"rice bowl with chicken",
	"spaghetti",
	"spaghetti with meat sauce",
	"spaghettios",
	"supper bakes meal kits",
	"swanson",
	"tortellini",
	"turkey",
	"turkey pot pie",
	};

	//34    Nut and Seed Products
	public static final String[] FG_15 = {
	
	"acorn",
	"acorns",
	"almond",
	"almonds",
	"beechnuts",
	"brazilnuts",
	"breadfruit",
	"breadnut",
	"butternuts",
	"cashew",
	"chestnuts",
	"chia",
	"coconut",
	"cottonseed",
	"flaxseed",
	"formulated",
	"ginkgo",
	"hazelnuts",
	"hickorynuts",
	"lotus",
	"macadamia",
	"mixed",
	"pecans",
	"pilinuts",
	"pine",
	"pistachio",
	"pumpkin",
	"safflower",
	"sesame",
	"sisymbrium",
	"sunflower",
	"walnuts",
	"watermelon",
	};

	//18    Pork Products
	public static final String[] FG_16 = {
	"backfat",
	"backribs",
		"bacon",
	"belly",
	"boneless",
	"carcas",
	"center", 
	"cured", 
	"enhanced",
	"ground",
	"hormel", 
	"leg",
	"loin",
	"oriental",
	"pickled", 
	"pre-sliced",
	"separable fat",
	"shoulder",
	"spareribs",
	"usda commodity",
	"variety meats"
	};

	//29    Poultry Products
	public static final String[] FG_17 = {
	 "bbq",
	 "broilers or fryers",
	"chicken breast tenders",
	"chicken nuggets",
	"chicken patty",
	"dove",
	"duck",
	"emu",
	"goose",
	"ground turkey",
	"guinea hen",
	"ostrich",
	"pate de foie gras",
	"pheasant",
	"poultry",
	"poultry food products",
	"quail",
	"squab",
	"turkey",
	"turkey and gravy",
	"turkey bacon",
	"turkey breast",
	"turkey from whole",
	"turkey patties",
	"turkey roast",
	"turkey sticks",
	"turkey thigh",
	"usda commodity",
	"usda commodity chicken",
	"canned",
	"capons",
	"cornish game hens",
	"feet",
	"gizzard",
	"ground",
	"heart",
	"liver",
	"roasting",
	"skin",
	"stewing",
	"flavored"
	
	
	};

	//6    Restaurant Foods
	public static final String[] FG_18 = {
	
	"applebee's",
	"cracker barrel",
	"denny's", 
	"t.g.i. friday's",
	"chinese",
	"latino",
	"family style"
	};

	//78    Sausages and Luncheon Meats
	public static final String[] FG_19 = {
	
	"bacon and beef sticks",
	"barbecue loaf",
	"beef",
	"beef sausage",
	"beerwurst",
	"blood sausage",
	"bockwurst",
	"bologna",
	"bratwurst",
	"braunschweiger (a liver sausage)",
	"brotwurst",
	"butcher boy meats",
	"carl buddig",
	"carl buddig. cooked smoked beef pastrami",
	"cheesefurter",
	"chicken breast",
	"chicken roll",
	"chicken spread",
	"chorizo",
	"corned beef loaf",
	"frankfurter",
	"ham",
	"ham and cheese loaf or roll",
	"ham and cheese spread",
	"ham salad spread",
	"headcheese",
	"honey loaf",
	"honey roll sausage",
	"hormel pillow pak sliced turkey pepperoni",
	"hormel spam",
	"hormel wrangler beef franks",
	"kielbasa",
	"knackwurst",
	"lebanon bologna",
	"liver cheese",
	"liver sausage",
	"liverwurst spread",
	"louis rich",
	"luncheon meat",
	"luncheon sausage",
	"luxury loaf",
	"macaroni and cheese loaf",
	"mortadella",
	"mother's loaf",
	"new england brand sausage",
	"olive loaf",
	"oscar mayer",
	"oscar mayer. bologna (wisconsin made ring)",
	"oven-roasted chicken breast roll",
	"pastrami",
	"pate",
	"peppered loaf",
	"pepperoni",
	"pickle and pimiento loaf",
	"picnic loaf",
	"polish sausage",
	"pork and beef sausage",
	"pork and turkey sausage",
	"pork sausage",
	"pork sausage rice links",
	"poultry salad sandwich spread",
	"roast beef spread",
	"salami",
	"sandwich spread",
	"sausage",
	"scrapple",
	"smoked link sausage",
	"swisswurst",
	"thuringer",
	"turkey",
	"turkey and pork sausage",
	"turkey breast",
	"turkey ham",
	"turkey roll",
	"turkey sausage",
	"usda commodity",
	"yachtwurst",
	};

	//62    Snacks
	public static final String[] FG_20 = {
	"bagel",
	"banana",
	"beef",
	"breakfast bar",
	"breakfast bars",
	"candy",
	"cheese puffs",
	"clif",
	"corn",
	"corn-based",
	"cornnuts",
	"cracker",
	"crisped",
	"farley",
	"formulated bar",
	"fritolay",
	"fruit",
	"general",
	"granola",
	"granola bar",
	"high",
	"kellogg",
	"kellogg's",
	"kraft",
	"low",
	"luna",
	"m&m",
	"mars",
	"microwave",
	"milk and",
	"nutri-grain",
	"oats",
	"oriental",
	"pita",
	"plantain",
	"popcorn",
	"pork",
	"potato",
	"potato chips",
	"power",
	"pretzels",
	"rice",
	"rice and",
	"rice cake",
	"sesame",
	"slim-fast",
	"snack", 
	"soft",
	"soy",
	"sugar",
	"sunkist",
	"sweet",
	"taro",
	"tortilla",
	"tortilla chips",
	"trail",
	"vegetable",
	"without",
	"yellow",
	"yucca",
	"zone",
	};

	//152    Soups, Sauces, and Gravies
	public static final String[] FG_21 = {
	"25%",
	"98%",
	"adobo",
	"alfredo", 
	"baked",
	"barbecue",
	"barbeque",
	"batman",
	"bbq",
	"bean",
	"beef",
	"beefy",
	"black",
	"blended",
	"bouillon",
	"broccoli",
	"brown",
	"campbell's", 
	"certified",
	"cheddar",
	"cheese",
	"chicken",
	"chili",
	"chipotle",  
	"cilantro",
	"clam",
	"classic",
	"cocktail",
	"consomme",
	"crab",
	"cream",
	"creamy",
	"curly",
	"diced",
	"dip",
	"dora",
	"double",
	"duck",
	"egg",
	"enchilada",
	"escarole",
	"fajita",
	"fiesta",
	"firehouse",
	"fish",
	"flavored",
	"franco-american",
	"french",
	"fresh",
	"garlic",
	"gazpacho",
	"golden",
	"goldfish",
	"gravy",
	"green",
	"grilled",
	"harvest",
	"healthy",
	"heart",
	"hearty",
	"heinz",
	"herb",
	"hoisin",
	"homemade",
	"homestyle",
	"honey",
	"hot",
	"instant",
	"italian",
	"italian-style",
	"lentil",
	"lime",
	"manhattan",
	"meat",
	"mediterranean",
	"mega",
	"mexican",
	"minestrone",
	"mini",
	"mole",
	"mushroom",
	"new",
	"old",
	"onion",
	"organic",
	"oxtail",
	"oyster", 
	"pace",
	"pasta",
	"pea",
	"pepper",
	"pepperpot",
	"peppers",
	"picante",
	"pico",
	"pizza",
	"plum",
	"pork",
	"potato",
	"prego",
	"ramen",
	"ready-to-serve", 
	"rigatoni",
	"roadhouse",
	"roasted",
	"salisbury",
	"salsa",
	"sauce",
	"savory",
	"scotch",
	"shark",
	"sirloin",
	"sizzlin'",
	"slow",
	"smoked",
	"sofrito", 
	"souper",
	"southwest",
	"southwestern",
	"southwestern-style",
	"spaghetti",
	"split",
	"steak",
	"stock",
	"stockpot",
	"swanson",
	"sweet",
	"tantalizin'",
	"tartar",
	"tequila",
	"teriyaki",
	"thick",
	"tomato",
	"tostitos",
	"traditional",
	"triple",
	"turkey",
	"unspecified",
	"usda",
	"vegetable",
	"vegetarian",
	"velvety", 
	"wonton",
	"worcestershire",
	"zesty",
	};

	//58    Spices and Herbs
	public static final String[] FG_22 = {
	"allspice",
	"anise",
	"balsamic",
	"basil",
	"bay",
	"canned",
	"capers",
	"caraway",
	"cardamom",
	"celery",
	"chervil",
	"chili",
	"cider",
	"cinnamon",
	"cloves",
	"coriander",
	"cumin",
	"curry",
	"dill",
	"distilled",
	"dried",
	"dry",
	"fennel",
	"fenugreek",
	"fresh",
	"garlic",
	"ginger",
	"horseradish",
	"imitation",
	"mace",
	"marjoram",
	"mustard",
	"nutmeg",
	"onion",
	"oregano",
	"pace",
	"paprika",
	"parsley",
	"pepper",
	"peppermint",
	"poppy",
	"poultry",
	"prepared",
	"pumpkin",
	"red",
	"rosemary",
	"saffron",
	"sage",
	"salt",
	"savory",
	"spearmint", 
	"table",
	"tarragon",
	"thyme",
	"turmeric",
	"vanilla",
	"vinegar",
	};

	//164    Sweets
	public static final String[] FG_23 = {
	"5th avenue",
	"all flavors",
	"almond joy",
	"apple",
	"apple crisp",
	"apricot",
	"baking chocolate",
	"banana",
	"blueberry",
	"breyers",
	"brown",
	"butterscotch",
	"butterscotch or", 
	"cane",
	"canned",
	"caramel custard",
	"caramello candy",
	"caramels",
	"carob",
	"cherry",
	"chewing gum", 
	"chocolate covered",
	"chocolate flavor",
	"chocolate-flavored hazelnut spread",
	"cocoa",
	"coconut cream",
	"coconut-nut",
	"confectioner's coating",
	"corn",
	"cream cheese-flavor",
	"crispy bar",
	"dark",
	"dark chocolate",
	"desserts",
	"dietetic",
	"dietetic (with",
	"divinity",
	"dry mix",
	"dry powder",
	"egg custard",
	"egg custards",
	"fat free",
	"flan",
	"flavors other",
	"fondant",
	"for baking",
	"french vanilla",
	"frostings",
	"frozen",
	"frozen novelites",
	"frozen novelties",
	"frozen yogurts",
	"fruit and",
	"fruit butters",
	"fruit leather",
	"fudge",
	"gelatin desserts",
	"gelatins",
	"glaze",
	"granulated",
	"grenadine",
	"gum drops",
	"gumdrops",
	"halavah",
	"hard",
	"heath bites",
	"hershey",
	"hershey's",
	"hershey's golden",
	"hershey's milk",
	"hershey's pot",
	"honey",
	"ice cream",
	"ice creams",
	"ice type",
	"jams and preserves",
	"jellies",
	"jellybeans",
	"juice type",
	"kit kat",
	"klondike",
	"krackel chocolate",
	"lemon",
	"liquid",
	"malt",
	"maple",
	"marmalade",
	"mars snackfood",
	"marshmallow cream",
	"marshmallows",
	"mexican",
	"milk chocolate",
	"milk dessert",
	"molasses",
	"mounds candy",
	"mousse",
	"mr. goodbar",
	"nestle",
	"no sugar",
	"nougat",
	"nuts in",
	"orange",
	"peanut bar",
	"peanut brittle",
	"pectin",
	"pie fillings",
	"pineapple",
	"powdered",
	"praline",
	"pudding",
	"puddings",
	"reduced sugar",
	"reese's",
	"reese's bites",
	"reese's fast",
	"reese's nutrageous",
	"reese's peanut",
	"reese's pieces",
	"regular",
	"rennin",
	"rice",
	"rolo caramels",
	"semisweet chocolate",
	"sesame crunch",
	"sherbet",
	"skor toffee",
	"snacks",
	"soft fruit",
	"sorghum",
	"special dark",
	"strawberry",
	"sugar",
	"sugar free",
	"sugar substitute",
	"sugar-coated almonds",
	"sugarless",
	"sugars",
	"sweet chocolate",
	"sweetener",
	"sweeteners",
	"symphony milk",
	"syrup",
	"syrups",
	"table blends",
	"tabletop",
	"taffy",
	"tapioca",
	"toffee",
	"tootsie roll",
	"toppings",
	"truffles",
	"turbinado",
	"twizzlers cherry",
	"twizzlers nibs",
	"twizzlers strawberry",
	"unsweetened",
	"vanilla",
	"whatchamacallit candy",
	"white",
	"white chocolate",
	"york bites",
	"york peppermint",
	};

	//301    Vegetables and Vegetable Products
	public static final String[] FG_24 = { 
	"agar",
	"alfalfa seeds",
	"amaranth leaves", 
	"arrowhead",
	"arrowroot",
	"artichokes",
	"arugula",
	"asparagus",  
	"balsam-pear (bitter gourd)",
	"bamboo shoots", 
	"beans",
	"beet greens",
	"beets", 
	"borage",
	"breaded",
	"broadbeans",
	"broccoli",
	"broccoli raab", 
	"brussels sprouts", 
	"burdock root",
	"butterbur", 
	"cabbage",
	"campbell's", 
	"canned",
	"cardoon",
	"carrot", 
	"cassava",
	"catsup",
	"cauliflower",
	"celeriac",
	"celery", 
	"celtuce",
	"chanterelle",
	"chard",
	"chayote",
	"chicory", 
	"chili",
	"chinese",
	"chives",  
	"cloud ears",
	"coleslaw",
	"collards",  
	"coriander (cilantro) leaves",
	"corn",   
	"cowpeas",  
	"cucumber",
	"dandelion greens",  
	"dishcloth (towelgourd)",
	"dock",
	"dried",
	"drumstick", 
	"edamame", 
	"eggplant",
	"endive",
	"enoki",
	"epazote",
	"eppaw",
	"fava",
	"fennel",
	"fiddlehead ferns",
	"fireweed",  
	"flowers",    
	"garden cress",				//only on secondary search
	"garland chrysanthemum",    //likewise
	"garlic",
	"ginger root",
	"gourd",
	"grape leaves",    
	"hawaii",   
	"hyacinth-beans",  
	"irishmoss",
	"jalapeno",  
	"jerusalem-artichokes",
	"jew's ear (pepeao)",  //only secondary 
	"jute",
	"kale",
	"kanpyo", 
	"kidney",
	"kohlrabi",
	"lambs quarters",
	"lambsquarters",  
	"leaves",
	"leeks",
	"lemon grass (citronella)",
	"lentils",
	"lettuce", 
	"lima beans",
	"lotus root", 
	"maitake mushrooms",    //only secondary search   
	"morel mushrooms",      // only secondary search
	"mountain yam", 
	"mung beans",
	"mushrooms",
	"mustard",   
	"navy",
	"new zealand spinach",
	"nopales", 
	"okra", 
	"onion",   
	"oyster",
	"pace",
	"palm hearts",    //needs to cover hearts of palm
	"parsley",
	"parsnips",
	"pasilla",
	"peas",   
	"pepeao",
	"pepper", 
	"pickle", 
	"pigeonpeas",
	"pimento",
	"pinto beans", //// secondary 
	"poi",
	"pokeberry shoots",
	"portabella",
	"potato",  
	"pumpkin", 
	"purslane",
	"radicchio", 
	"radish",
	"raw",    //199 raw 
	"root", 
	"rutabagas",
	"salsify",
	"sauerkraut",  
	"seaweed", 
	"sesbania flower",
	"shallots", 
	"shiitake",
	"shoots",
	"snap",
	"soybeans",
	"spinach",   
	"sprouted",
	"squash", 
	"straw mushrooms",    //secondary
	"succotash",    
	"sweet potato",  
	"taro", 
	"tomatillos",
	"tomato", 
	"tree fern", 
	"turnip", 
	"v8", 
	"vegetable",
	"vinespinach", 
	"wasabi",
	"waterchestnuts",
	"watercress",
	"waxgourd",   
	"winged bean",  
	"yam",
	"yambean (jicama)",
	"yardlong bean",
	"yautia (tannier)",
	"yeast extract spread", 
	"zucchini",
	};

	static final String[][] FOODGROUPS	 = {FG_0  ,
		FG_1  ,
		FG_2  ,
		FG_3  ,
		FG_4  ,
		FG_5  ,
		FG_6  ,
		FG_7  ,
		FG_8  ,
		FG_9  ,
		FG_10  ,
		FG_11  ,
		FG_12  ,
		FG_13  ,
		FG_14  ,
		FG_15  ,
		FG_16  ,
		FG_17  ,
		FG_18  ,
		FG_19  ,
		FG_20  ,
		FG_21  ,
		FG_22  ,
		FG_23  ,
		FG_24  
		};
}
